### PR TITLE
FNV: adding the sanity checks extension as a requirement

### PR DESCRIPTION
**Pull request by IDCs**
This allows us to avoid committing directly to our games repo while also ensuring that the extension is up to date with the game's latest trends.

closes https://github.com/Nexus-Mods/vortex-games/pull/121

### CODE REVIEW

**Comment by Senjay-id** [comment]
I really need someone to test this function because I want to merge it to the sanity check, I couldn't find anyone willing to test this and my pc uses nvidia gpu
```js
function amdDriverVersionCheck() {
    exec('wmic path win32_VideoController get caption, driverVersion', (error, stdout, stderr) => {
        if (error) {
            log('warn', `Error getting gpu information: ${error.message}`);
            return;
        }
        if (stderr) {
            log('warn', `Command error: ${stderr}`);
            return;
        }

        const content = stdout.trim();
        const lines = content.split('\n').map(line => line.trim());
        const dataLines = lines.slice(1);
        const amdGPUs = [];

        dataLines.forEach(line => {
            const match = line.match(/(.+?)\s{2,}(.+)/);
            if (match) {
                const gpuBrand = match[1].trim();
                const driverVersion = match[2].trim();
                if (/amd/i.test(gpuBrand))
                    amdGPUs.push({ gpuBrand, driverVersion });
            }
        });
        if (amdGPUs.length === 0) {
            log('debug', 'No AMD GPU found.');
            return;
        } else {
            const incompatibleVersions = [
                '24.1.1', '24.2.1', '24.3.1', '24.4.1', '24.5.1'
            ];

            amdGPUs.forEach(gpu => {
                if (incompatibleVersions.includes(gpu.driverVersion)) {
                    api.sendNotification({
                        id: 'fnvsanitycheck-brokenamdgpuversion',
                        type: 'warning',
                        message: 'Incompatible driver version',
                        allowSuppress: true,
                        actions: [
                            {
                                title: 'More',
                                action: dismiss => {
                                    const t = api.translate;
                                    api.showDialog('error', 'Incompatible AMD driver version', {
                                        bbcode: t(`Warning: Your AMD GPU driver version ${gpu.driverVersion} is known to crash the game.[br][/br]`
                                            + `Driver version 24.1.1 up to 24.5.1 may fail to compile the shader and crash. The known issue is stated in the official AMD website [url=https://www.amd.com/en/resources/support-articles/release-notes/RN-RAD-WIN-24-4-1.html]here[/url][br][/br][br][/br]`
                                            + `Please update your driver to 24.6.1 or later.`)
                                    }, [
                                        { label: 'Ok' },
                                        { label: 'Ignore', action: () => api.suppressNotification(`fnvsanitycheck-brokenamdgpuversion`) }
                                    ]);
                                },
                            },
                        ],
                    });
                }
                else
                    log('debug', 'The AMD GPU Driver version is compatible/up-to-date')
            });
        }
    });
}
```

**Comment by IDCs** [comment]
Hey @Senjay-id,

Unfortunately WMIC is being deprecated in the future (I think Microsoft Server OS's have already removed it), so I'm afraid that function should not be added to the sanity checks extension!

If you really want to add this check reliably - it will have to use WINAPI, so either have to be a separate C# application which Vortex can run and test the drivers; or a Node API native module.

Both seem overkill to me TBH. You could just have a suppressible notification stating that AMD users should be aware of those driver versions.

**Comment by Senjay-id** [comment]
I see, I'll change it to suppressible notification without checking the user gpu.

**Comment by Senjay-id** [comment]
image

**Comment by Senjay-id** [comment]
image

**Comment by Senjay-id** [comment]
@IDCs Hi, just checking back to see when will this be implemented since it's been over a month.

**Pull request merged**
