### PR TITLE
Add Subnautica: Below Zero game support

### PR DESCRIPTION
**Pull request by AlexejheroYTB**
Subnautica and Subnautica: Below Zero run on the same QModManager mod framework.
I would prefer that the info.json files for these games are kept the same and updated both at once.

### CODE REVIEW

**Comment by TanninOne** [comment]
Apologies I overlooked this PR until now.
I'm not sure what you mean by your comment though, did you change anything on the original Subnautica?

**Comment by AlexejheroYTB** [comment]
No, what I meant was that if one of the vortex games is updated, the other one should be too

**Comment by AlexejheroYTB** [comment]
Also, i forgot to mention, this wasn't ready for merge. The epic games game code and the artwork need to be updated.

**Comment by AlexejheroYTB** [comment]
I can address these issues in another pr, if needed (i kinda forgot too)

**Pull request merged**
