### PR TITLE
Quick Fix to Update 7 Load Order in Baldur's Gate 3

### PR DESCRIPTION
**Pull request by SCBionicle**
fixes: Nexus-Mods/Vortex#16384

### CODE REVIEW

**Comment by SCBionicle** [comment]
Tested on the following functions:
Export to file, export to game, import from game, import from file.

**Comment by SCBionicle** [comment]
Tested on Import from BG3MM

**Comment by SCBionicle** [comment]
Ready for review

**Comment by SCBionicle** [comment]
Stumbled across dev instructions, marking as draft until changes replicated in type script.

**Comment by IDCs** [comment]
Hi there - first of all thank you for your submission. I'm afraid that your PR is not backwards compatible with patch 6 (apparently many users chose not to update yet) and unfortunately falls short in certain areas to fully support both versions.

Going to close this as the required changes have been added in: https://github.com/Nexus-Mods/vortex-games/pull/132

**Pull request closed without merging**
