### PR TITLE
Add My Summer Car support

### PR DESCRIPTION
**Pull request by joestringer**
Relies upon the user first installing ModLoader[[0][0]] into the Steam game
directory. Tested with various mods pulled from nexusmods with different
inner archive formats, as well as ModAPI[[1][1]] from GitHub.

Manages the mods directly from the game directory in order to allow
Vehicle Texture Swap[[2][2]] to inject custom files under `Images/`.

Save games and car skins are not supported.

Tested with:

* Modloader v1.1.16
* Carry More v1.4.3-1-1-4-3
* ChaseCamera-117-1-4-1-1586542271
* Cinder Block Jack Stands-17-1-1-1540849644
* DonnerTechRacing ECU-205-1-4-11-1607720814
* DonnerTechRacing Turbocharger-174-2-1-7-1600462221
* ExtraPaintables 1-764-1-1-1622730656
* FastTravel-116-1-0-1-1585441105
* GT_Interior_dll-91-1-4-1631342460
* GifuAddonV1.5-48-1-5-1573053957
* GitHubPkg_ModApi.v0.1.4.1-alpha
* Grabanything.zip-460-1-4-3-1609428236
* JonnezFuelGauge-217-1-0-1587583466
* Lights On Switches-868-1-0-1627381356
* Minimap-326-1-0-4-1625672763
* MosquitoKill-28-1-0-1545183342
* NotepadUI-148-1-1-1604067214
* My Summer Fishing Trip-173-1-1-4-1621127136
* Noclip(Flymod).zip-462-1-4-0-1609437601
* Quicksave 1.0-524-1-0-1611884635
* RallyTimes-975-1-0-1631011627
* SecureWarningTriangle-1030-0-1-1632576948
* SecureSpareTire V0.1.2b-1017-0-1-2b-1632576051
* ShiftLight-305-1-0-0-1598433783
* Show Bolt Sizes-55-v2-1-1558347114
* The Ruscko Restoration Project-61-1-2-1-1558433625
* Vehicle Texture Swap-4-5-0-1557711436
* VehicleRamps-644-1-0-0-1616952257
* Wear Inspector Reborn-806-1-0-1623715853

[0]: https://www.nexusmods.com/mysummercar/mods/147
[1]: https://github.com/tommojphillips/ModAPI
[2]: https://www.nexusmods.com/mysummercar/mods/4

Fixes: https://github.com/Nexus-Mods/Vortex/issues/5838

### CODE REVIEW

**Comment by IDCs** [comment]
Hi @joestringer - I've looked through your code and it should be fine to merge; however, have you considered uploading your extension on the website instead ? https://www.nexusmods.com/site

If uploaded to the main repo, your extension's update rate would be mostly limited to us building a new Vortex release, while if uploaded to the site, your extension would still be present within Vortex yet your updates will become available to the userbase within 24 hours of you making a new version.

**Comment by joestringer** [comment]
Hi @IDCs , I glanced at the option there but frankly it seemed like a complicated procedure for a one-off weekend project. If I upload the code here and submit a PR, we can easily discuss if there are obviously missing pieces but otherwise it's basically just a matter of getting the code lined up correctly and 🚢 .

I've tried to submit on the website, here's my feedback on the process:
* Looking around on the website. There's no obvious way to submit extensions. Is an extension a mod? I'm not sure.
* Can I find similar extensions to Vortex? Hmm, the search box doesn't have an extensions option, only "mods", "games", "images", "videos", "users".
* Is there something at the top of the page or the bottom of the page? No, I see no way to submit an extension.
* Nexus Mods isn't a game... or is it? Wait, it is! 😮 
* OK let me submit a mod for Nexus Mods through the [Upload a Mod page](https://www.nexusmods.com/site/mods/add). Wait there are 9 dedicated steps? Do I have to do all of these?
* Mod details... OK I know this should have a name and it'll help if I specify that this is a user extension. I don't care about creating an overview and also a description, this is just game support. Next!
* Media. I don't have any media to share here, it's just game support. Oh good, I can skip this. Next!
* Documentation. Honestly it's pretty unlikely that I submit additional versions, but sure I'll describe the version I'm putting out. Next!
* Permissions. I don't care, this is the first time I used nexus mods for > 1 year, I don't interact with the community much (for better or worse - my impressions are pretty positive, I just don't spend a lot of time modding games).
  * User permissions? Fine, sure. Let people do what they want. I assume the defaults are good.
  * Distribution? I appreciate that you're trying to protect mod authors but the GPL v3 license on the repo here is fine, this is just trying to extend an existing GPLv3 app with support for a new game. I'm not submitting any special sauce. Licenses are honestly pretty complicated but I know roughly what GPLv3 means (and sites like choosealicense.com can help, [GPLv3](https://choosealicense.com/licenses/gpl-3.0/)). Admittedly maybe this makes me unusual and most mod authors want to submit rights individually through this page, I appreciate that.
  * Only tricky bit is that the guide to [Creating a game extension for Vortex](https://wiki.nexusmods.com/index.php/Creating_a_game_extension_for_Vortex) suggests to reuse images from the nexusmods website for which I can't attest to the rights. 🤔 My process for this was that I just searched for the game and downloaded the image from the search page. If I click through, there's no way to find the image again and no way to find the author. I presume that y'all have rights to redistribute the image already so by uploading it here in the PR, I'm leveraging whatever rights you have gained from the original submitter. I _could_ go and create a new image, but the game extension guide suggests against using a different image so then.. am I supposed to create a new image that is representative of the game and then also submit that for use as the main game image? (Needless to say, I feel like I'm overthinking it at this point..)
* Requirements or mirrors, ok easy there is none. Next!
* Add a new file. Now wait, the extension requires at least the image, json info, javascript index file. How am I supposed to send this in, submit individual files? Zip them up? Should they all be directly in the zip or nested inside somewhere? Am I in the right place, this still doesn't look like an extension submission page? How do I know this will work correctly when I submit the files? 
  * Strictly speaking, I don't know that this PR will work correctly from this repository either, but it at least matches the layout as though I cloned this repository into my `%appdata%\Vortex\plugins` directory. Worst case, I could test this out when y'all make the next release.
* OK assuming I figured out the last part, now it wants me to write an article. What does this mean? Why do I care? Still not sure if I'm in the right place. Well I guess I can skip it, OK.
* Publish mod.. OK this makes sense I guess I can just click the button to publish it. (spoiler: I wasn't confident enough about my prior answers to do so).
* I didn't publish, but clicked out and when I revisit the mod it's apparent that there is a requirement for one image. Seems weird to submit an image with a screenshot of the extension working in Vortex if the goal is for Vortex users to not worry about this but just naturally get the extension by default.

I don't want this to come off the wrong way. Using the "creating a game extension for Vortex" guide + a few reference copies on the repo, I was able to get a lot further than I expected, despite not having a lot of experience with Javascript. I think it's pretty cool that with a reasonable level of programming proficiency, a few hours, and a problem, I was able to extend Vortex to do what I wanted to do. I'm far more familiar with Git/GitHub than I am with Nexus Mods so it's quite possible that I just completely missed some obvious "submit an extension button" or something so I'd welcome any pointers in that direction. And if not, maybe my feedback above can help describe why I'm here on Github submitting a PR rather than using the Nexus Mods website to get this extension included.

As for submitting through Nexus Mods, I think that with a few extra pointers I'd be open to doing so but I'll be up front - I tested this to work with a variety of mods I am using right now as I play the game, but I'll likely stop playing soon and stop maintaining this plugin code. If it's useful to someone else in the current state, then I'm happy to spent a bit more time helping to share it. I think the main two open points from the upload process above are what I'm supposed to do about permissions and formatting the upload. But also if the code looks reasonable then I'd be happy to just push it through here. If it turns out that there's a bug, if we're lucky I'll find it & submit another PR to fix it up. Or maybe someone else will find it here and fix it up, who knows?

**Comment by IDCs** [comment]
Hi @joestringer, thank you for the in-depth feedback - I agree that the website's upload mechanism is overly complicated and not clear enough where Vortex extensions are concerned (You were indeed on the right track!); unfortunately the mod upload site is out of our (Vortex team) control, but we will most definitely forward your notes to our colleagues on the web team.

We are looking to implement a simpler way for game extension developers to register their extension with Vortex without having to go through Nexus Mods (yep, we will be using Github for that), but I'm afraid that's still somewhat a long way off.

To be clear, I have no doubt your game extension is currently fully working, the code is decent and I've even tested it a bit. our concern is that as a rule, once a game extension is permanently bundled with the Vortex installer, the game extension must always be distributed in a functional state; which will obviously force us to maintain it ourselves if anything breaks in a future game update. Given that we're only two developers with a mountain load of work, we're apprehensive about bundling extensions of games we don't actively play and/or are not aware of its modding patterns.

Although this game seems to be using the "standard" Unity3D mod loader/injector pattern; we would prefer if you upload your extension to the website. You were indeed on the right track, the image you add in the mod upload page will be displayed to users within Vortex on the extensions dashlet. I suggest using the gameart you added in the extension - our community managers @Pickysaurus will help you find a different image if you do not wish to use that one.

In terms of packaging the extension for distribution please follow the following wiki article (spoiler: index file, info json file and art should be zipped up, no nesting of any kind, they should be at the archive's root): https://wiki.nexusmods.com/index.php/Packaging_extensions_for_Vortex

If you have any issues with the upload process, please feel free to tag me or @Pickysaurus and we will try to help. (alternatively you can get in contact with us on Discord)

**Comment by joestringer** [comment]
OK great, your explanation makes total sense. I also didn't see the "Packaging extensions for Vortex" page before, that helps. I was able to figure out how to upload the extension and publish it. Thanks for your help @IDCs.

**Pull request closed without merging**
